language: bash
os: linux
dist: bionic

git:
  depth: 1

jobs:
  include:
    - stage: master
      if: branch = master
      addons:
        apt:
          packages:
          - jq
          - python3
      cache:
        directories:

      before_install:

      script:
         - .arm/scripts/buildBoardsManagerPackage.sh
         
      notifications:
        email:
          on_success: change
          on_failure: change
